// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1051:不要声明可见实例字段", Justification = "<挂起>", Scope = "member", Target = "~F:NineSunScripture.strategy.MainStrategy.RWLockSlimForHighFreqPrice")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1305:指定 IFormatProvider", Justification = "<挂起>", Scope = "member", Target = "~M:NineSunScripture.db.StockDbHelper.DataRowToModel(System.Data.DataRow)~NineSunScripture.model.Quotes")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Interoperability", "CA1401:P/Invokes 应该是不可见的", Justification = "<挂起>", Scope = "member", Target = "~M:NineSunScripture.trade.structApi.api.PriceAPI.HQ_PushData(System.Int32,System.Int32,System.String,System.String,NineSunScripture.trade.structApi.api.PriceAPI.PushCallback,System.Boolean)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:标识符不应包含下划线", Justification = "<挂起>", Scope = "member", Target = "~M:NineSunScripture.trade.structApi.api.PriceAPI.HQ_PushData(System.Int32,System.Int32,System.String,System.String,NineSunScripture.trade.structApi.api.PriceAPI.PushCallback,System.Boolean)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:指定 StringComparison", Justification = "<挂起>", Scope = "member", Target = "~M:NineSunScripture.strategy.MainStrategy.OnPushResult(System.Int32,System.IntPtr)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:请不要将文本作为本地化参数传递", Justification = "<挂起>", Scope = "member", Target = "~M:NineSunScripture.MainForm.TsmiSwitch_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:请不要将文本作为本地化参数传递", Justification = "<挂起>", Scope = "member", Target = "~M:NineSunScripture.MainForm.#ctor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Interoperability", "CA1401:P/Invokes 应该是不可见的", Justification = "<挂起>", Scope = "member", Target = "~M:NineSunScripture.trade.structApi.api.PriceAPI.HQ_Logoff(System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:标识符不应包含下划线", Justification = "<挂起>", Scope = "member", Target = "~M:NineSunScripture.trade.structApi.api.PriceAPI.HQ_Logoff(System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA2101:指定对 P/Invoke 字符串参数进行封送处理", Justification = "<挂起>", Scope = "member", Target = "~M:NineSunScripture.trade.structApi.api.PriceAPI.HQ_PushData(System.Int32,System.Int32,System.String,System.String,NineSunScripture.trade.structApi.api.PriceAPI.PushCallback,System.Boolean)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2000:丢失范围之前释放对象", Justification = "<挂起>", Scope = "member", Target = "~M:NineSunScripture.util.Utils.SendEmail(System.String,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:指定 StringComparison", Justification = "<挂起>", Scope = "member", Target = "~M:NineSunScripture.util.Utils.ifNeedToSubOByOPrice(NineSunScripture.model.Quotes)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:不捕获常规异常类型", Justification = "<挂起>", Scope = "member", Target = "~M:NineSunScripture.strategy.MainStrategy.ExeContBoardStrategyByStock(NineSunScripture.model.Quotes)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1051:不要声明可见实例字段", Justification = "<挂起>", Scope = "member", Target = "~F:NineSunScripture.model.Quotes.Code")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:不捕获常规异常类型", Justification = "<挂起>", Scope = "member", Target = "~M:NineSunScripture.forms.AddStockForm.TbCode_TextChanged(System.Object,System.EventArgs)")]
